# Generated by Django 5.1.1 on 2024-09-09 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
