# Generated by Django 5.1.1 on 2024-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
