# Generated by Django 5.1.3 on 2024-12-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0004_userprofile_remove_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='CLT',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='NBM',
            field=models.FloatField(default=0),
        ),
    ]
