# Generated by Django 5.1.3 on 2024-12-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0005_user_clt_user_nbm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='CLT',
            field=models.FloatField(default=300),
        ),
    ]
