# Generated by Django 5.1.3 on 2024-12-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0006_alter_user_clt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='CLT',
        ),
        migrations.RemoveField(
            model_name='user',
            name='NBM',
        ),
    ]
