# Generated by Django 5.1.3 on 2024-12-09 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0007_remove_user_clt_remove_user_nbm'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyGB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=1024)),
                ('GB', models.IntegerField(default=0)),
            ],
        ),
    ]
