# Generated by Django 5.1.3 on 2024-12-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_cardsuser_alter_graphicscard_mh'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=1024)),
                ('CLT', models.FloatField(default=300)),
                ('NBM', models.FloatField(default=0)),
            ],
        ),
    ]
