# Generated by Django 5.1.3 on 2024-12-06 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_tokens'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiningStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('is_mining', models.BooleanField(default=False)),
            ],
        ),
    ]
