# Generated by Django 5.1.3 on 2024-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0004_miningstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=1024)),
                ('order_type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], max_length=4)),
                ('amount', models.FloatField()),
                ('price_per_unit', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
            ],
        ),
    ]
