# Generated by Django 5.1.1 on 2024-10-17 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_fileupload_extension'),
        ('regauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='regauth.user'),
        ),
    ]
