# Generated by Django 5.1.1 on 2024-10-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_fileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
