# Generated by Django 5.1.1 on 2024-10-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_fileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x73f29e354460>', max_length=255),
        ),
    ]
