# Generated by Django 5.1.1 on 2024-10-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_alter_fileupload_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='user',
            field=models.UUIDField(default=''),
        ),
    ]
