# Generated by Django 5.1.1 on 2024-11-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_fileupload_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='password',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
