# Generated by Django 5.1.1 on 2024-11-06 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_fileupload_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='password',
        ),
    ]
