# Generated by Django 5.1.3 on 2024-11-17 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_remove_folder_parent_folder_alter_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
