# Generated by Django 5.1.3 on 2024-11-18 16:11

import files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_alter_folder_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to=files.models.upload_to),
        ),
    ]
