# Generated by Django 5.1.3 on 2024-11-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_alter_fileupload_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=128)),
                ('size', models.IntegerField(default=0)),
            ],
        ),
    ]
