# Generated by Django 5.1.1 on 2024-10-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.UUIDField(default=''),
        ),
    ]
