# Generated by Django 5.1.1 on 2024-10-31 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='display_mode',
            field=models.CharField(default='GRID', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='file_sort',
            field=models.CharField(default='DATE', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='language',
            field=models.CharField(default='RU', max_length=10),
        ),
        migrations.AddField(
            model_name='settings',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='storage_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='theme',
            field=models.CharField(default='DARK', max_length=10),
        ),
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
