# Generated by Django 5.1.1 on 2024-10-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_settings_display_mode_settings_file_sort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='user',
            field=models.UUIDField(default=''),
        ),
    ]
